database:
  dsn : "root:root1234@tcp(127.0.0.1:3306)/gvb?charset=utf8mb4&parseTime=True&loc=Local"
  maxIdleConns: 11
  maxOpenConns: 100

#logger:
#  level: info
#  prefix: '[gvb]'
#  director: log
#  show_line: true
#  log_in_console: true

app:
  name: gv_blog
  port: 8080
  env: dev